In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
x1 = tf.constant([1,0,3,0,5], tf.float32) #공부한 시간
x2 = tf.constant([0,2,3,4,5], tf.float32) #출석일수
y = tf.constant([1,2,3,4,5], tf.float32) #받은 점수

In [6]:
w1 = tf.Variable(tf.random_uniform([1]))
w2 = tf.Variable(tf.random_uniform([1]))
b = tf.Variable(tf.random_uniform([1]))

In [7]:
hx = w1*x1 + w2*x2 + b
cost = tf.reduce_mean(tf.square(hx-y))

In [8]:
optimizer = tf.train.GradientDescentOptimizer(0.1)#learning rate
train = optimizer.minimize( cost )

In [9]:
sess = tf.Session()
init =tf.global_variables_initializer()
sess.run( init)

In [10]:
for i in range(100):
    sess.run(train)
    print(i, sess.run(cost))

0 3.7901616
1 3.5921657
2 3.406791
3 3.2332122
4 3.0706584
5 2.9184105
6 2.7757952
7 2.642184
8 2.5169888
9 2.3996615
10 2.289688
11 2.1865888
12 2.0899167
13 1.999252
14 1.9142044
15 1.8344069
16 1.7595189
17 1.689221
18 1.623214
19 1.5612193
20 1.5029764
21 1.4482416
22 1.3967876
23 1.3484017
24 1.3028843
25 1.2600504
26 1.2197267
27 1.1817496
28 1.1459687
29 1.112242
30 1.080437
31 1.0504293
32 1.022104
33 0.99535245
34 0.97007406
35 0.94617444
36 0.9235649
37 0.90216315
38 0.8818917
39 0.8626792
40 0.8444576
41 0.8271645
42 0.8107408
43 0.79513174
44 0.7802855
45 0.76615417
46 0.75269306
47 0.73985964
48 0.7276153
49 0.71592295
50 0.70474833
51 0.6940594
52 0.6838263
53 0.6740209
54 0.664617
55 0.65559006
56 0.646917
57 0.63857645
58 0.63054883
59 0.62281495
60 0.61535746
61 0.60815984
62 0.6012071
63 0.5944843
64 0.5879789
65 0.5816775
66 0.57556885
67 0.5696417
68 0.5638861
69 0.5582923
70 0.55285126
71 0.5475547
72 0.54239464
73 0.53736377
74 0.5324552
75 0.5276624
76 0.52297926

In [11]:
sess.run(w1)

array([0.44005567], dtype=float32)

In [12]:
sess.run(w2)

array([0.5103654], dtype=float32)

In [13]:
sess.run(b)

array([0.7130583], dtype=float32)