In [1]:
import numpy as np

In [2]:
data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
data

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
data.shape

(4, 3)

In [4]:
data[0] #0행

array([1, 2, 3])

In [5]:
data[[0,3]] #0행 3행

array([[ 1,  2,  3],
       [10, 11, 12]])

In [6]:
data[[0]]

array([[1, 2, 3]])

In [7]:
data[0,1] #0행1열

2

In [8]:
data[1:] #1행 부터 끝까지

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
data[1:, 2]

array([ 6,  9, 12])

In [10]:
data[1:, 1:]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [11]:
data[:,1:]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [12]:
data[:,[0,2]]

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

In [ ]:
# 데이터프레임.iloc[]