In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn import preprocessing #전처리...
import matplotlib.pyplot as plt

In [2]:
data = [[828, 920, 1234567, 1020, 1111],
        [824, 910, 2345612, 1090, 1234],
        [880, 900, 3456123, 1010, 1000],
        [870, 990, 2312123, 1001, 1122],
        [860, 980, 3223123, 1008, 1133],
        [850, 970, 2432123, 1100, 1221]]
data = np.float32(data)

In [3]:
xdata = data[:,:-1] #0:4 0<= col<4  0<=col<-1
ydata = data[:,[-1]]

In [4]:
ydata

array([[1111.],
       [1234.],
       [1000.],
       [1122.],
       [1133.],
       [1221.]], dtype=float32)

In [5]:
x = tf.placeholder(tf.float32,shape=[None,4])
y = tf.constant( ydata, tf.float32)

w = tf.Variable( tf.random_uniform([4,1] ) )
b = tf.Variable( tf.random_uniform([1] ) )

hx = tf.matmul( x,w) +b
cost = tf.reduce_mean( tf.square(hx-y) )

optimizer = tf.train.GradientDescentOptimizer( 0.01 )
train = optimizer.minimize( cost )
sess = tf.Session()
init =tf.global_variables_initializer()
sess.run( init)
for i in range( 10000):
    sess.run( train, {x:xdata})
    print( i, sess.run(cost, {x:xdata}))

0 5.0300797e+34
1 inf
2 inf
3 inf
4 nan
5 nan
6 nan
7 nan
8 nan
9 nan
10 nan
11 nan
12 nan
13 nan
14 nan
15 nan
16 nan
17 nan
18 nan
19 nan
20 nan
21 nan
22 nan
23 nan
24 nan
25 nan
26 nan
27 nan
28 nan
29 nan
30 nan
31 nan
32 nan
33 nan
34 nan
35 nan
36 nan
37 nan
38 nan
39 nan
40 nan
41 nan
42 nan
43 nan
44 nan
45 nan
46 nan
47 nan
48 nan
49 nan
50 nan
51 nan
52 nan
53 nan
54 nan
55 nan
56 nan
57 nan
58 nan
59 nan
60 nan
61 nan
62 nan
63 nan
64 nan
65 nan
66 nan
67 nan
68 nan
69 nan
70 nan
71 nan
72 nan
73 nan
74 nan
75 nan
76 nan
77 nan
78 nan
79 nan
80 nan
81 nan
82 nan
83 nan
84 nan
85 nan
86 nan
87 nan
88 nan
89 nan
90 nan
91 nan
92 nan
93 nan
94 nan
95 nan
96 nan
97 nan
98 nan
99 nan
100 nan
101 nan
102 nan
103 nan
104 nan
105 nan
106 nan
107 nan
108 nan
109 nan
110 nan
111 nan
112 nan
113 nan
114 nan
115 nan
116 nan
117 nan
118 nan
119 nan
120 nan
121 nan
122 nan
123 nan
124 nan
125 nan
126 nan
127 nan
128 nan
129 nan
130 nan
131 nan
132 nan
133 nan
134 nan
135 nan
136 nan
137 

1129 nan
1130 nan
1131 nan
1132 nan
1133 nan
1134 nan
1135 nan
1136 nan
1137 nan
1138 nan
1139 nan
1140 nan
1141 nan
1142 nan
1143 nan
1144 nan
1145 nan
1146 nan
1147 nan
1148 nan
1149 nan
1150 nan
1151 nan
1152 nan
1153 nan
1154 nan
1155 nan
1156 nan
1157 nan
1158 nan
1159 nan
1160 nan
1161 nan
1162 nan
1163 nan
1164 nan
1165 nan
1166 nan
1167 nan
1168 nan
1169 nan
1170 nan
1171 nan
1172 nan
1173 nan
1174 nan
1175 nan
1176 nan
1177 nan
1178 nan
1179 nan
1180 nan
1181 nan
1182 nan
1183 nan
1184 nan
1185 nan
1186 nan
1187 nan
1188 nan
1189 nan
1190 nan
1191 nan
1192 nan
1193 nan
1194 nan
1195 nan
1196 nan
1197 nan
1198 nan
1199 nan
1200 nan
1201 nan
1202 nan
1203 nan
1204 nan
1205 nan
1206 nan
1207 nan
1208 nan
1209 nan
1210 nan
1211 nan
1212 nan
1213 nan
1214 nan
1215 nan
1216 nan
1217 nan
1218 nan
1219 nan
1220 nan
1221 nan
1222 nan
1223 nan
1224 nan
1225 nan
1226 nan
1227 nan
1228 nan
1229 nan
1230 nan
1231 nan
1232 nan
1233 nan
1234 nan
1235 nan
1236 nan
1237 nan
1238 nan
1239 nan
1

2287 nan
2288 nan
2289 nan
2290 nan
2291 nan
2292 nan
2293 nan
2294 nan
2295 nan
2296 nan
2297 nan
2298 nan
2299 nan
2300 nan
2301 nan
2302 nan
2303 nan
2304 nan
2305 nan
2306 nan
2307 nan
2308 nan
2309 nan
2310 nan
2311 nan
2312 nan
2313 nan
2314 nan
2315 nan
2316 nan
2317 nan
2318 nan
2319 nan
2320 nan
2321 nan
2322 nan
2323 nan
2324 nan
2325 nan
2326 nan
2327 nan
2328 nan
2329 nan
2330 nan
2331 nan
2332 nan
2333 nan
2334 nan
2335 nan
2336 nan
2337 nan
2338 nan
2339 nan
2340 nan
2341 nan
2342 nan
2343 nan
2344 nan
2345 nan
2346 nan
2347 nan
2348 nan
2349 nan
2350 nan
2351 nan
2352 nan
2353 nan
2354 nan
2355 nan
2356 nan
2357 nan
2358 nan
2359 nan
2360 nan
2361 nan
2362 nan
2363 nan
2364 nan
2365 nan
2366 nan
2367 nan
2368 nan
2369 nan
2370 nan
2371 nan
2372 nan
2373 nan
2374 nan
2375 nan
2376 nan
2377 nan
2378 nan
2379 nan
2380 nan
2381 nan
2382 nan
2383 nan
2384 nan
2385 nan
2386 nan
2387 nan
2388 nan
2389 nan
2390 nan
2391 nan
2392 nan
2393 nan
2394 nan
2395 nan
2396 nan
2397 nan
2

3475 nan
3476 nan
3477 nan
3478 nan
3479 nan
3480 nan
3481 nan
3482 nan
3483 nan
3484 nan
3485 nan
3486 nan
3487 nan
3488 nan
3489 nan
3490 nan
3491 nan
3492 nan
3493 nan
3494 nan
3495 nan
3496 nan
3497 nan
3498 nan
3499 nan
3500 nan
3501 nan
3502 nan
3503 nan
3504 nan
3505 nan
3506 nan
3507 nan
3508 nan
3509 nan
3510 nan
3511 nan
3512 nan
3513 nan
3514 nan
3515 nan
3516 nan
3517 nan
3518 nan
3519 nan
3520 nan
3521 nan
3522 nan
3523 nan
3524 nan
3525 nan
3526 nan
3527 nan
3528 nan
3529 nan
3530 nan
3531 nan
3532 nan
3533 nan
3534 nan
3535 nan
3536 nan
3537 nan
3538 nan
3539 nan
3540 nan
3541 nan
3542 nan
3543 nan
3544 nan
3545 nan
3546 nan
3547 nan
3548 nan
3549 nan
3550 nan
3551 nan
3552 nan
3553 nan
3554 nan
3555 nan
3556 nan
3557 nan
3558 nan
3559 nan
3560 nan
3561 nan
3562 nan
3563 nan
3564 nan
3565 nan
3566 nan
3567 nan
3568 nan
3569 nan
3570 nan
3571 nan
3572 nan
3573 nan
3574 nan
3575 nan
3576 nan
3577 nan
3578 nan
3579 nan
3580 nan
3581 nan
3582 nan
3583 nan
3584 nan
3585 nan
3

4634 nan
4635 nan
4636 nan
4637 nan
4638 nan
4639 nan
4640 nan
4641 nan
4642 nan
4643 nan
4644 nan
4645 nan
4646 nan
4647 nan
4648 nan
4649 nan
4650 nan
4651 nan
4652 nan
4653 nan
4654 nan
4655 nan
4656 nan
4657 nan
4658 nan
4659 nan
4660 nan
4661 nan
4662 nan
4663 nan
4664 nan
4665 nan
4666 nan
4667 nan
4668 nan
4669 nan
4670 nan
4671 nan
4672 nan
4673 nan
4674 nan
4675 nan
4676 nan
4677 nan
4678 nan
4679 nan
4680 nan
4681 nan
4682 nan
4683 nan
4684 nan
4685 nan
4686 nan
4687 nan
4688 nan
4689 nan
4690 nan
4691 nan
4692 nan
4693 nan
4694 nan
4695 nan
4696 nan
4697 nan
4698 nan
4699 nan
4700 nan
4701 nan
4702 nan
4703 nan
4704 nan
4705 nan
4706 nan
4707 nan
4708 nan
4709 nan
4710 nan
4711 nan
4712 nan
4713 nan
4714 nan
4715 nan
4716 nan
4717 nan
4718 nan
4719 nan
4720 nan
4721 nan
4722 nan
4723 nan
4724 nan
4725 nan
4726 nan
4727 nan
4728 nan
4729 nan
4730 nan
4731 nan
4732 nan
4733 nan
4734 nan
4735 nan
4736 nan
4737 nan
4738 nan
4739 nan
4740 nan
4741 nan
4742 nan
4743 nan
4744 nan
4

5844 nan
5845 nan
5846 nan
5847 nan
5848 nan
5849 nan
5850 nan
5851 nan
5852 nan
5853 nan
5854 nan
5855 nan
5856 nan
5857 nan
5858 nan
5859 nan
5860 nan
5861 nan
5862 nan
5863 nan
5864 nan
5865 nan
5866 nan
5867 nan
5868 nan
5869 nan
5870 nan
5871 nan
5872 nan
5873 nan
5874 nan
5875 nan
5876 nan
5877 nan
5878 nan
5879 nan
5880 nan
5881 nan
5882 nan
5883 nan
5884 nan
5885 nan
5886 nan
5887 nan
5888 nan
5889 nan
5890 nan
5891 nan
5892 nan
5893 nan
5894 nan
5895 nan
5896 nan
5897 nan
5898 nan
5899 nan
5900 nan
5901 nan
5902 nan
5903 nan
5904 nan
5905 nan
5906 nan
5907 nan
5908 nan
5909 nan
5910 nan
5911 nan
5912 nan
5913 nan
5914 nan
5915 nan
5916 nan
5917 nan
5918 nan
5919 nan
5920 nan
5921 nan
5922 nan
5923 nan
5924 nan
5925 nan
5926 nan
5927 nan
5928 nan
5929 nan
5930 nan
5931 nan
5932 nan
5933 nan
5934 nan
5935 nan
5936 nan
5937 nan
5938 nan
5939 nan
5940 nan
5941 nan
5942 nan
5943 nan
5944 nan
5945 nan
5946 nan
5947 nan
5948 nan
5949 nan
5950 nan
5951 nan
5952 nan
5953 nan
5954 nan
5

6994 nan
6995 nan
6996 nan
6997 nan
6998 nan
6999 nan
7000 nan
7001 nan
7002 nan
7003 nan
7004 nan
7005 nan
7006 nan
7007 nan
7008 nan
7009 nan
7010 nan
7011 nan
7012 nan
7013 nan
7014 nan
7015 nan
7016 nan
7017 nan
7018 nan
7019 nan
7020 nan
7021 nan
7022 nan
7023 nan
7024 nan
7025 nan
7026 nan
7027 nan
7028 nan
7029 nan
7030 nan
7031 nan
7032 nan
7033 nan
7034 nan
7035 nan
7036 nan
7037 nan
7038 nan
7039 nan
7040 nan
7041 nan
7042 nan
7043 nan
7044 nan
7045 nan
7046 nan
7047 nan
7048 nan
7049 nan
7050 nan
7051 nan
7052 nan
7053 nan
7054 nan
7055 nan
7056 nan
7057 nan
7058 nan
7059 nan
7060 nan
7061 nan
7062 nan
7063 nan
7064 nan
7065 nan
7066 nan
7067 nan
7068 nan
7069 nan
7070 nan
7071 nan
7072 nan
7073 nan
7074 nan
7075 nan
7076 nan
7077 nan
7078 nan
7079 nan
7080 nan
7081 nan
7082 nan
7083 nan
7084 nan
7085 nan
7086 nan
7087 nan
7088 nan
7089 nan
7090 nan
7091 nan
7092 nan
7093 nan
7094 nan
7095 nan
7096 nan
7097 nan
7098 nan
7099 nan
7100 nan
7101 nan
7102 nan
7103 nan
7104 nan
7

8077 nan
8078 nan
8079 nan
8080 nan
8081 nan
8082 nan
8083 nan
8084 nan
8085 nan
8086 nan
8087 nan
8088 nan
8089 nan
8090 nan
8091 nan
8092 nan
8093 nan
8094 nan
8095 nan
8096 nan
8097 nan
8098 nan
8099 nan
8100 nan
8101 nan
8102 nan
8103 nan
8104 nan
8105 nan
8106 nan
8107 nan
8108 nan
8109 nan
8110 nan
8111 nan
8112 nan
8113 nan
8114 nan
8115 nan
8116 nan
8117 nan
8118 nan
8119 nan
8120 nan
8121 nan
8122 nan
8123 nan
8124 nan
8125 nan
8126 nan
8127 nan
8128 nan
8129 nan
8130 nan
8131 nan
8132 nan
8133 nan
8134 nan
8135 nan
8136 nan
8137 nan
8138 nan
8139 nan
8140 nan
8141 nan
8142 nan
8143 nan
8144 nan
8145 nan
8146 nan
8147 nan
8148 nan
8149 nan
8150 nan
8151 nan
8152 nan
8153 nan
8154 nan
8155 nan
8156 nan
8157 nan
8158 nan
8159 nan
8160 nan
8161 nan
8162 nan
8163 nan
8164 nan
8165 nan
8166 nan
8167 nan
8168 nan
8169 nan
8170 nan
8171 nan
8172 nan
8173 nan
8174 nan
8175 nan
8176 nan
8177 nan
8178 nan
8179 nan
8180 nan
8181 nan
8182 nan
8183 nan
8184 nan
8185 nan
8186 nan
8187 nan
8

9245 nan
9246 nan
9247 nan
9248 nan
9249 nan
9250 nan
9251 nan
9252 nan
9253 nan
9254 nan
9255 nan
9256 nan
9257 nan
9258 nan
9259 nan
9260 nan
9261 nan
9262 nan
9263 nan
9264 nan
9265 nan
9266 nan
9267 nan
9268 nan
9269 nan
9270 nan
9271 nan
9272 nan
9273 nan
9274 nan
9275 nan
9276 nan
9277 nan
9278 nan
9279 nan
9280 nan
9281 nan
9282 nan
9283 nan
9284 nan
9285 nan
9286 nan
9287 nan
9288 nan
9289 nan
9290 nan
9291 nan
9292 nan
9293 nan
9294 nan
9295 nan
9296 nan
9297 nan
9298 nan
9299 nan
9300 nan
9301 nan
9302 nan
9303 nan
9304 nan
9305 nan
9306 nan
9307 nan
9308 nan
9309 nan
9310 nan
9311 nan
9312 nan
9313 nan
9314 nan
9315 nan
9316 nan
9317 nan
9318 nan
9319 nan
9320 nan
9321 nan
9322 nan
9323 nan
9324 nan
9325 nan
9326 nan
9327 nan
9328 nan
9329 nan
9330 nan
9331 nan
9332 nan
9333 nan
9334 nan
9335 nan
9336 nan
9337 nan
9338 nan
9339 nan
9340 nan
9341 nan
9342 nan
9343 nan
9344 nan
9345 nan
9346 nan
9347 nan
9348 nan
9349 nan
9350 nan
9351 nan
9352 nan
9353 nan
9354 nan
9355 nan
9

In [6]:
# 1. learning rate 아주작게
# 2. optimizer Adam
# 3. normalize (정규화)

In [7]:
scale = preprocessing.MinMaxScaler()
dataN = scale.fit_transform( data )

In [8]:
dataN

array([[0.0714283 , 0.22222233, 0.        , 0.19191933, 0.47435904],
       [0.        , 0.11111164, 0.50012016, 0.89899063, 1.0000005 ],
       [1.        , 0.        , 1.        , 0.09090996, 0.        ],
       [0.8214283 , 1.        , 0.48504567, 0.        , 0.52136755],
       [0.6428566 , 0.8888893 , 0.8951186 , 0.07070732, 0.56837654],
       [0.4642849 , 0.7777777 , 0.5390618 , 1.        , 0.94444466]],
      dtype=float32)

In [9]:
xdata = dataN[:,:-1] #0:4 0<= col<4  0<=col<-1
ydata = dataN[:,[-1]]

In [10]:
x = tf.placeholder(tf.float32,shape=[None,4])
y = tf.constant( ydata, tf.float32)

w = tf.Variable( tf.random_uniform([4,1] ) )
b = tf.Variable( tf.random_uniform([1] ) )

hx = tf.matmul( x,w) +b
cost = tf.reduce_mean( tf.square(hx-y) )

optimizer = tf.train.GradientDescentOptimizer( 0.01 )
train = optimizer.minimize( cost )
sess = tf.Session()
init =tf.global_variables_initializer()
sess.run( init)
for i in range( 10000):
    sess.run( train, {x:xdata})
    print( i, sess.run(cost, {x:xdata}))

0 1.9635286
1 1.8179666
2 1.6839852
3 1.5606551
4 1.4471222
5 1.3426003
6 1.2463673
7 1.1577579
8 1.0761617
9 1.0010157
10 0.93180305
11 0.8680484
12 0.8093145
13 0.7551989
14 0.70533174
15 0.65937275
16 0.617009
17 0.5779527
18 0.54193944
19 0.50872535
20 0.47808686
21 0.44981802
22 0.42372942
23 0.39964673
24 0.37740982
25 0.35687134
26 0.33789584
27 0.32035872
28 0.30414513
29 0.28914973
30 0.27527568
31 0.26243353
32 0.25054142
33 0.23952371
34 0.22931117
35 0.21983981
36 0.21105099
37 0.2028907
38 0.19530916
39 0.18826075
40 0.18170343
41 0.17559844
42 0.16991027
43 0.16460615
44 0.15965606
45 0.15503223
46 0.15070923
47 0.14666356
48 0.14287369
49 0.13931982
50 0.13598363
51 0.13284837
52 0.12989856
53 0.12712
54 0.12449959
55 0.12202533
56 0.11968607
57 0.1174717
58 0.11537278
59 0.11338065
60 0.11148742
61 0.10968575
62 0.107968874
63 0.106330656
64 0.10476532
65 0.10326762
66 0.10183277
67 0.10045624
68 0.09913394
69 0.097862095
70 0.09663727
71 0.09545619
72 0.09431592
73 0.0

617 0.012982178
618 0.012972056
619 0.012961962
620 0.012951903
621 0.012941882
622 0.012931888
623 0.012921936
624 0.012912014
625 0.012902122
626 0.012892261
627 0.01288244
628 0.012872645
629 0.012862884
630 0.012853153
631 0.012843453
632 0.012833789
633 0.012824153
634 0.012814545
635 0.012804967
636 0.0127954185
637 0.012785907
638 0.012776422
639 0.012766962
640 0.012757535
641 0.012748134
642 0.012738767
643 0.012729424
644 0.012720113
645 0.012710822
646 0.01270157
647 0.01269234
648 0.012683132
649 0.012673959
650 0.012664807
651 0.012655684
652 0.01264659
653 0.012637517
654 0.012628471
655 0.012619451
656 0.0126104625
657 0.012601498
658 0.012592555
659 0.012583636
660 0.012574741
661 0.0125658745
662 0.012557034
663 0.012548213
664 0.012539421
665 0.01253065
666 0.012521905
667 0.012513177
668 0.012504477
669 0.012495804
670 0.012487148
671 0.012478519
672 0.012469915
673 0.0124613205
674 0.012452762
675 0.012444218
676 0.012435702
677 0.012427203
678 0.012418731
679 0.012

1345 0.008751658
1346 0.008747701
1347 0.008743747
1348 0.008739798
1349 0.008735851
1350 0.008731906
1351 0.0087279705
1352 0.008724034
1353 0.008720094
1354 0.008716167
1355 0.008712239
1356 0.008708316
1357 0.008704393
1358 0.008700475
1359 0.008696557
1360 0.008692646
1361 0.008688738
1362 0.008684828
1363 0.008680924
1364 0.008677027
1365 0.008673127
1366 0.008669236
1367 0.008665343
1368 0.008661456
1369 0.008657567
1370 0.008653686
1371 0.0086498065
1372 0.008645932
1373 0.008642059
1374 0.00863819
1375 0.008634324
1376 0.008630459
1377 0.0086266
1378 0.008622739
1379 0.0086188875
1380 0.008615034
1381 0.008611184
1382 0.008607338
1383 0.008603492
1384 0.008599656
1385 0.008595817
1386 0.0085919835
1387 0.00858815
1388 0.008584322
1389 0.0085804975
1390 0.008576675
1391 0.008572857
1392 0.00856904
1393 0.0085652275
1394 0.00856142
1395 0.00855761
1396 0.008553808
1397 0.008550002
1398 0.008546204
1399 0.00854241
1400 0.008538619
1401 0.008534825
1402 0.00853104
1403 0.0085272575

1860 0.0070662363
1861 0.007063549
1862 0.007060869
1863 0.007058192
1864 0.0070555154
1865 0.0070528383
1866 0.007050166
1867 0.007047497
1868 0.0070448276
1869 0.007042162
1870 0.0070394953
1871 0.007036831
1872 0.007034171
1873 0.0070315115
1874 0.007028854
1875 0.0070261993
1876 0.0070235473
1877 0.007020898
1878 0.0070182444
1879 0.0070156003
1880 0.007012952
1881 0.007010311
1882 0.007007668
1883 0.0070050284
1884 0.0070023914
1885 0.006999752
1886 0.006997123
1887 0.006994491
1888 0.0069918595
1889 0.006989235
1890 0.0069866036
1891 0.006983981
1892 0.0069813584
1893 0.0069787395
1894 0.0069761216
1895 0.0069735036
1896 0.006970888
1897 0.006968277
1898 0.006965665
1899 0.00696306
1900 0.0069604497
1901 0.0069578434
1902 0.0069552423
1903 0.006952641
1904 0.0069500417
1905 0.0069474443
1906 0.0069448496
1907 0.0069422536
1908 0.006939661
1909 0.006937075
1910 0.0069344877
1911 0.006931901
1912 0.006929317
1913 0.006926734
1914 0.006924151
1915 0.0069215745
1916 0.006918997
1917 

2515 0.005667983
2516 0.005666312
2517 0.005664643
2518 0.0056629777
2519 0.005661311
2520 0.0056596478
2521 0.0056579844
2522 0.005656322
2523 0.0056546633
2524 0.0056529995
2525 0.005651342
2526 0.005649686
2527 0.0056480304
2528 0.005646374
2529 0.0056447214
2530 0.00564307
2531 0.005641418
2532 0.0056397673
2533 0.0056381174
2534 0.0056364723
2535 0.0056348233
2536 0.005633181
2537 0.0056315344
2538 0.005629891
2539 0.00562825
2540 0.0056266114
2541 0.00562497
2542 0.0056233327
2543 0.005621694
2544 0.00562006
2545 0.005618423
2546 0.0056167915
2547 0.005615158
2548 0.0056135263
2549 0.005611898
2550 0.00561027
2551 0.0056086406
2552 0.0056070127
2553 0.005605389
2554 0.005603764
2555 0.0056021404
2556 0.005600517
2557 0.005598897
2558 0.0055972785
2559 0.0055956617
2560 0.0055940426
2561 0.005592426
2562 0.005590812
2563 0.005589198
2564 0.0055875867
2565 0.0055859736
2566 0.0055843615
2567 0.005582752
2568 0.0055811466
2569 0.0055795386
2570 0.005577935
2571 0.005576329
2572 0.00

3053 0.0049223737
3054 0.0049212384
3055 0.004920104
3056 0.004918967
3057 0.0049178344
3058 0.004916702
3059 0.0049155704
3060 0.004914439
3061 0.0049133096
3062 0.0049121776
3063 0.004911049
3064 0.0049099214
3065 0.0049087927
3066 0.0049076676
3067 0.0049065426
3068 0.004905416
3069 0.0049042907
3070 0.0049031703
3071 0.0049020457
3072 0.0049009263
3073 0.004899802
3074 0.0048986836
3075 0.0048975623
3076 0.0048964457
3077 0.004895328
3078 0.0048942105
3079 0.004893094
3080 0.0048919786
3081 0.0048908642
3082 0.004889749
3083 0.0048886356
3084 0.0048875264
3085 0.0048864144
3086 0.004885304
3087 0.0048841946
3088 0.004883083
3089 0.0048819757
3090 0.004880869
3091 0.0048797624
3092 0.004878657
3093 0.004877552
3094 0.0048764446
3095 0.0048753433
3096 0.00487424
3097 0.0048731393
3098 0.0048720376
3099 0.004870937
3100 0.0048698373
3101 0.0048687374
3102 0.0048676403
3103 0.004866542
3104 0.004865445
3105 0.0048643504
3106 0.004863255
3107 0.004862162
3108 0.0048610694
3109 0.0048599

3677 0.0043497295
3678 0.004349002
3679 0.0043482743
3680 0.0043475465
3681 0.0043468215
3682 0.0043460936
3683 0.004345365
3684 0.0043446408
3685 0.0043439153
3686 0.0043431916
3687 0.0043424666
3688 0.0043417416
3689 0.0043410216
3690 0.004340299
3691 0.0043395744
3692 0.004338856
3693 0.0043381345
3694 0.0043374132
3695 0.004336694
3696 0.0043359734
3697 0.0043352554
3698 0.004334537
3699 0.004333818
3700 0.0043331
3701 0.0043323836
3702 0.004331667
3703 0.0043309517
3704 0.0043302365
3705 0.004329521
3706 0.0043288074
3707 0.004328093
3708 0.004327379
3709 0.0043266662
3710 0.0043259547
3711 0.0043252436
3712 0.0043245303
3713 0.004323821
3714 0.0043231086
3715 0.0043223985
3716 0.004321692
3717 0.004320983
3718 0.0043202722
3719 0.004319567
3720 0.004318858
3721 0.004318152
3722 0.004317446
3723 0.004316741
3724 0.0043160347
3725 0.004315331
3726 0.004314625
3727 0.004313921
3728 0.00431322
3729 0.0043125176
3730 0.0043118135
3731 0.0043111113
3732 0.00431041
3733 0.00430971
3734 

4385 0.003944197
4386 0.003943755
4387 0.003943317
4388 0.003942878
4389 0.003942437
4390 0.0039419984
4391 0.0039415574
4392 0.003941119
4393 0.003940683
4394 0.003940244
4395 0.003939806
4396 0.0039393683
4397 0.003938932
4398 0.0039384943
4399 0.003938058
4400 0.00393762
4401 0.003937186
4402 0.0039367513
4403 0.0039363154
4404 0.0039358805
4405 0.003935444
4406 0.0039350116
4407 0.0039345766
4408 0.003934144
4409 0.0039337105
4410 0.0039332765
4411 0.003932845
4412 0.0039324122
4413 0.0039319787
4414 0.0039315466
4415 0.003931115
4416 0.0039306832
4417 0.0039302534
4418 0.0039298227
4419 0.0039293934
4420 0.0039289636
4421 0.003928533
4422 0.0039281035
4423 0.0039276723
4424 0.003927246
4425 0.003926818
4426 0.0039263894
4427 0.00392596
4428 0.0039255335
4429 0.0039251074
4430 0.0039246785
4431 0.0039242534
4432 0.003923825
4433 0.0039234003
4434 0.0039229738
4435 0.0039225477
4436 0.0039221216
4437 0.0039216974
4438 0.003921274
4439 0.0039208494
4440 0.0039204266
4441 0.0039200014

5056 0.0037089859
5057 0.0037087102
5058 0.003708439
5059 0.0037081658
5060 0.003707892
5061 0.0037076175
5062 0.0037073467
5063 0.0037070755
5064 0.003706801
5065 0.003706531
5066 0.003706259
5067 0.0037059877
5068 0.0037057165
5069 0.0037054427
5070 0.003705174
5071 0.0037049036
5072 0.003704632
5073 0.003704361
5074 0.0037040927
5075 0.0037038224
5076 0.0037035532
5077 0.003703283
5078 0.003703015
5079 0.0037027437
5080 0.0037024757
5081 0.0037022058
5082 0.0037019392
5083 0.003701669
5084 0.0037014019
5085 0.0037011327
5086 0.0037008652
5087 0.003700597
5088 0.0037003297
5089 0.00370006
5090 0.0036997937
5091 0.0036995271
5092 0.00369926
5093 0.0036989946
5094 0.0036987262
5095 0.0036984608
5096 0.0036981956
5097 0.00369793
5098 0.0036976635
5099 0.003697398
5100 0.003697133
5101 0.003696868
5102 0.003696603
5103 0.0036963385
5104 0.0036960728
5105 0.0036958102
5106 0.003695544
5107 0.0036952812
5108 0.0036950177
5109 0.0036947532
5110 0.0036944884
5111 0.0036942258
5112 0.00369396

5578 0.0035896553
5579 0.0035894662
5580 0.003589278
5581 0.003589091
5582 0.0035889007
5583 0.003588713
5584 0.003588523
5585 0.0035883344
5586 0.0035881486
5587 0.0035879628
5588 0.0035877738
5589 0.0035875868
5590 0.003587397
5591 0.0035872106
5592 0.003587025
5593 0.003586837
5594 0.0035866487
5595 0.0035864655
5596 0.0035862774
5597 0.0035860902
5598 0.0035859046
5599 0.0035857195
5600 0.003585533
5601 0.0035853472
5602 0.0035851607
5603 0.0035849763
5604 0.0035847898
5605 0.0035846059
5606 0.0035844203
5607 0.003584233
5608 0.0035840494
5609 0.0035838636
5610 0.0035836808
5611 0.0035834957
5612 0.0035833113
5613 0.0035831265
5614 0.0035829432
5615 0.00358276
5616 0.0035825763
5617 0.0035823912
5618 0.0035822073
5619 0.0035820256
5620 0.0035818415
5621 0.0035816578
5622 0.0035814748
5623 0.0035812913
5624 0.003581107
5625 0.0035809258
5626 0.0035807441
5627 0.0035805602
5628 0.0035803795
5629 0.003580197
5630 0.0035800142
5631 0.0035798328
5632 0.0035796526
5633 0.0035794696
5634 

6251 0.0034886375
6252 0.0034885209
6253 0.003488403
6254 0.0034882864
6255 0.00348817
6256 0.0034880526
6257 0.0034879365
6258 0.0034878198
6259 0.003487704
6260 0.003487587
6261 0.0034874715
6262 0.003487355
6263 0.0034872398
6264 0.0034871213
6265 0.0034870075
6266 0.0034868896
6267 0.0034867742
6268 0.00348666
6269 0.0034865458
6270 0.0034864282
6271 0.0034863127
6272 0.0034861953
6273 0.0034860831
6274 0.0034859655
6275 0.0034858512
6276 0.0034857374
6277 0.003485622
6278 0.003485507
6279 0.0034853911
6280 0.0034852764
6281 0.003485162
6282 0.003485046
6283 0.0034849334
6284 0.0034848189
6285 0.0034847048
6286 0.0034845907
6287 0.0034844775
6288 0.0034843609
6289 0.0034842484
6290 0.0034841348
6291 0.0034840193
6292 0.0034839064
6293 0.0034837946
6294 0.0034836791
6295 0.0034835648
6296 0.0034834538
6297 0.0034833376
6298 0.0034832258
6299 0.003483113
6300 0.003483
6301 0.003482885
6302 0.0034827723
6303 0.003482661
6304 0.0034825464
6305 0.0034824351
6306 0.003482322
6307 0.00348

6792 0.0034360534
6793 0.003435973
6794 0.003435894
6795 0.0034358145
6796 0.0034357337
6797 0.0034356546
6798 0.0034355763
6799 0.0034354946
6800 0.0034354178
6801 0.0034353386
6802 0.003435259
6803 0.0034351796
6804 0.0034351007
6805 0.0034350222
6806 0.0034349437
6807 0.003434863
6808 0.0034347845
6809 0.0034347065
6810 0.003434627
6811 0.00343455
6812 0.0034344692
6813 0.003434391
6814 0.003434311
6815 0.003434234
6816 0.0034341577
6817 0.0034340757
6818 0.0034340003
6819 0.0034339211
6820 0.003433842
6821 0.0034337642
6822 0.003433685
6823 0.0034336087
6824 0.0034335305
6825 0.0034334518
6826 0.003433374
6827 0.0034332965
6828 0.0034332203
6829 0.003433141
6830 0.0034330646
6831 0.0034329873
6832 0.0034329097
6833 0.003432832
6834 0.0034327547
6835 0.003432678
6836 0.0034325998
6837 0.0034325223
6838 0.0034324443
6839 0.003432367
6840 0.00343229
6841 0.003432214
6842 0.0034321372
6843 0.0034320608
6844 0.0034319845
6845 0.0034319058
6846 0.0034318313
6847 0.0034317542
6848 0.00343

7459 0.003393703
7460 0.003393653
7461 0.0033936047
7462 0.0033935544
7463 0.0033935066
7464 0.0033934556
7465 0.003393406
7466 0.0033933579
7467 0.0033933073
7468 0.003393259
7469 0.0033932093
7470 0.0033931609
7471 0.003393111
7472 0.0033930624
7473 0.0033930123
7474 0.0033929616
7475 0.0033929136
7476 0.003392867
7477 0.0033928163
7478 0.0033927662
7479 0.0033927185
7480 0.0033926691
7481 0.0033926193
7482 0.003392571
7483 0.0033925232
7484 0.0033924745
7485 0.0033924244
7486 0.0033923767
7487 0.0033923276
7488 0.0033922791
7489 0.0033922296
7490 0.0033921811
7491 0.0033921332
7492 0.0033920847
7493 0.0033920368
7494 0.0033919876
7495 0.0033919408
7496 0.003391891
7497 0.0033918421
7498 0.0033917949
7499 0.0033917457
7500 0.0033916973
7501 0.0033916503
7502 0.0033916018
7503 0.0033915548
7504 0.0033915068
7505 0.0033914587
7506 0.0033914093
7507 0.0033913609
7508 0.0033913134
7509 0.0033912659
7510 0.0033912165
7511 0.0033911709
7512 0.0033911217
7513 0.003391073
7514 0.0033910263
7

7989 0.0033717826
7990 0.003371749
7991 0.0033717155
7992 0.003371682
7993 0.0033716478
7994 0.0033716124
7995 0.0033715798
7996 0.003371545
7997 0.0033715123
7998 0.0033714771
7999 0.0033714427
8000 0.0033714084
8001 0.0033713775
8002 0.0033713419
8003 0.0033713076
8004 0.003371276
8005 0.0033712406
8006 0.003371207
8007 0.0033711742
8008 0.00337114
8009 0.0033711055
8010 0.0033710732
8011 0.003371041
8012 0.0033710066
8013 0.0033709735
8014 0.0033709388
8015 0.0033709062
8016 0.0033708739
8017 0.0033708382
8018 0.0033708059
8019 0.0033707723
8020 0.0033707398
8021 0.003370705
8022 0.0033706732
8023 0.0033706387
8024 0.003370606
8025 0.0033705726
8026 0.0033705395
8027 0.0033705058
8028 0.0033704732
8029 0.0033704394
8030 0.003370406
8031 0.0033703747
8032 0.0033703402
8033 0.0033703058
8034 0.0033702746
8035 0.0033702406
8036 0.0033702098
8037 0.0033701763
8038 0.0033701435
8039 0.00337011
8040 0.0033700785
8041 0.0033700445
8042 0.003370012
8043 0.003369978
8044 0.0033699467
8045 0.

8623 0.003354396
8624 0.0033543762
8625 0.0033543536
8626 0.0033543305
8627 0.00335431
8628 0.003354287
8629 0.0033542665
8630 0.003354244
8631 0.0033542234
8632 0.0033542004
8633 0.0033541804
8634 0.0033541594
8635 0.003354137
8636 0.003354116
8637 0.003354095
8638 0.0033540723
8639 0.003354052
8640 0.0033540297
8641 0.003354009
8642 0.0033539862
8643 0.0033539655
8644 0.0033539438
8645 0.0033539233
8646 0.0033539024
8647 0.0033538789
8648 0.0033538584
8649 0.0033538372
8650 0.0033538146
8651 0.0033537957
8652 0.0033537736
8653 0.0033537531
8654 0.00335373
8655 0.0033537096
8656 0.0033536877
8657 0.0033536663
8658 0.0033536477
8659 0.0033536234
8660 0.0033536048
8661 0.003353582
8662 0.0033535622
8663 0.0033535399
8664 0.0033535205
8665 0.003353498
8666 0.0033534782
8667 0.0033534567
8668 0.0033534353
8669 0.0033534141
8670 0.0033533936
8671 0.003353373
8672 0.0033533517
8673 0.0033533303
8674 0.0033533087
8675 0.0033532882
8676 0.0033532695
8677 0.0033532449
8678 0.0033532258
8679 0.

9129 0.0033451698
9130 0.0033451535
9131 0.0033451386
9132 0.0033451237
9133 0.0033451086
9134 0.003345091
9135 0.0033450776
9136 0.003345063
9137 0.0033450474
9138 0.0033450322
9139 0.0033450185
9140 0.0033450022
9141 0.0033449878
9142 0.0033449726
9143 0.0033449568
9144 0.003344942
9145 0.0033449268
9146 0.0033449128
9147 0.0033448979
9148 0.0033448816
9149 0.003344868
9150 0.0033448522
9151 0.0033448385
9152 0.0033448217
9153 0.003344809
9154 0.0033447922
9155 0.0033447787
9156 0.003344763
9157 0.0033447482
9158 0.0033447342
9159 0.0033447193
9160 0.0033447037
9161 0.0033446886
9162 0.0033446734
9163 0.0033446597
9164 0.0033446446
9165 0.0033446308
9166 0.003344614
9167 0.0033445992
9168 0.0033445843
9169 0.0033445705
9170 0.0033445563
9171 0.0033445412
9172 0.0033445265
9173 0.003344511
9174 0.0033444976
9175 0.0033444809
9176 0.0033444685
9177 0.003344452
9178 0.0033444401
9179 0.0033444234
9180 0.0033444099
9181 0.0033443964
9182 0.0033443794
9183 0.0033443654
9184 0.0033443514
9

9779 0.0033372801
9780 0.0033372694
9781 0.00333726
9782 0.0033372499
9783 0.0033372417
9784 0.0033372324
9785 0.0033372224
9786 0.0033372135
9787 0.0033372035
9788 0.0033371923
9789 0.0033371833
9790 0.0033371728
9791 0.003337165
9792 0.0033371558
9793 0.003337147
9794 0.0033371355
9795 0.0033371265
9796 0.0033371171
9797 0.0033371074
9798 0.0033370967
9799 0.0033370883
9800 0.003337079
9801 0.0033370715
9802 0.003337061
9803 0.003337051
9804 0.0033370417
9805 0.0033370315
9806 0.0033370226
9807 0.0033370126
9808 0.0033370033
9809 0.0033369947
9810 0.0033369858
9811 0.003336976
9812 0.0033369663
9813 0.003336956
9814 0.0033369476
9815 0.0033369383
9816 0.0033369316
9817 0.0033369206
9818 0.0033369109
9819 0.0033369001
9820 0.003336894
9821 0.0033368852
9822 0.0033368748
9823 0.0033368648
9824 0.003336855
9825 0.0033368457
9826 0.0033368357
9827 0.003336828
9828 0.003336819
9829 0.0033368103
9830 0.0033368005
9831 0.0033367893
9832 0.003336781
9833 0.003336773
9834 0.003336763
9835 0.0

In [11]:
sess.run(w)

array([[-0.5903023 ],
       [ 0.45694682],
       [ 0.18254668],
       [ 0.44165573]], dtype=float32)

In [12]:
sess.run(b)

array([0.3815744], dtype=float32)

In [13]:
[828, 920, 1234567, 1020]
# sess.run( hx, {x:[[828, 920, 1234567, 1020]]})

[828, 920, 1234567, 1020]

In [14]:
arr = scale.transform( [[828, 920, 1234567, 1020,None]] )
arr[:,:-1]

array([[7.14281425e-02, 2.22222470e-01, 1.00739044e-08, 1.91919606e-01]])

In [15]:
sess.run( hx, {x:arr[:,:-1]} )

array([[0.5257164]], dtype=float32)

In [16]:
f = scale.inverse_transform([[None,None,None,None,0.52571404]])

In [17]:
f[:,-1]

array([1123.01702611])

In [25]:
labelScale = preprocessing.MinMaxScaler()
y1 = labelScale.fit_transform( data[:,[-1]] )
y1

array([[0.47435904],
       [1.0000005 ],
       [0.        ],
       [0.52136755],
       [0.56837654],
       [0.94444466]], dtype=float32)

In [26]:
aa = sess.run( hx, {x:arr[:,:-1]} )

In [27]:
labelScale.inverse_transform(aa )

array([[1123.0176]], dtype=float32)