In [ ]:
# bostonhousing.csv 데이터 이용하여 w, b값을 구하고 
# 0.00632	18	2.31	0	0.538	6.575	65.2	4.09	1	296	15.3	396.9	4.98	24
# 데이터로 추택가격을 예측하시요
# 데이터로 주택가격을 예측하시요
# 정규화 하시요 


In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import preprocessing  # 전처리....

In [3]:
data = pd.read_csv('data/BostonHousing.csv')

In [4]:
data = np.array(data)

In [5]:
xdata = data[:,:-1]
ydata = data[:,[-1]]

In [6]:
feature_scale = preprocessing.MinMaxScaler()
xdataN = feature_scale.fit_transform(xdata)

label_scale = preprocessing.MinMaxScaler()
ydataN = label_scale.fit_transform(ydata)

In [15]:
x = tf.placeholder(tf.float32, shape=[None,13])
y = tf.constant(ydataN, tf.float32)
w = tf.Variable(tf.random_uniform([13,1]))
b = tf.Variable(tf.random_uniform([1]))

hx = tf.matmul(x,w) + b
cost = tf.reduce_mean(tf.square(hx-y))

optimizer = tf.train.AdamOptimizer(0.1) #learning rate
train = optimizer.minimize(cost)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

for i in range(10000):
    sess.run(train, {x:xdataN})
#     print(i, sess.run(cost, {x:xdataN}))    

In [8]:
sess.run(w)

array([[-0.21269485],
       [ 0.10401191],
       [ 0.01331842],
       [ 0.06056044],
       [-0.19102408],
       [ 0.44271508],
       [ 0.00234897],
       [-0.35973713],
       [ 0.15728064],
       [-0.14277425],
       [-0.19816299],
       [ 0.08291816],
       [-0.4217501 ]], dtype=float32)

In [9]:
sess.run(b)

array([0.4813055], dtype=float32)

In [10]:
# arr = feature_scale.transform([[0.00632 ,18 ,2.31 ,0 ,0.538 ,6.575, 65.2 ,4.09 ,1 ,296 ,15.3 ,396.9 ,4.98 ]])
arr = feature_scale.transform(xdata[[0],:])
label_scale.inverse_transform(sess.run(hx, {x:arr}))

array([[30.182268]], dtype=float32)