In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# 공부한시간, 출석일수
xdata = [[1,3],[2,2],[3,1],[4,6],[5,5],[6,4]]
ydata = [[0],[0],[0],[1],[1],[1]] #0불합격 1 합격

In [3]:
x = tf.placeholder(tf.float32,shape=[None,2] )
y = tf.constant( ydata, tf.float32)

In [4]:
w = tf.Variable( tf.random_uniform([2,1]) )
b = tf.Variable( tf.random_uniform([1]) )

In [5]:
z = tf.matmul(x,w) + b
hx = tf.nn.sigmoid( z ) # 0~ 1사이값

In [6]:
# cost_i = y*(-tf.log(hx))+(1-y)*(-tf.log(1-hx))
cost_i =tf.nn.sigmoid_cross_entropy_with_logits(logits=z, labels=y)
cost = tf.reduce_mean( cost_i )

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [7]:
optimizer = tf.train.GradientDescentOptimizer( 0.1 )
train = optimizer.minimize( cost )
sess = tf.Session()
init =tf.global_variables_initializer()
sess.run( init)

In [8]:
for i in range(1000):
    sess.run( train, {x:xdata})
    print( i, sess.run(cost, {x:xdata}))

0 1.570274
1 1.368384
2 1.1793393
3 1.0103018
4 0.87155795
5 0.7740338
6 0.7203512
7 0.69789433
8 0.68915504
9 0.6843235
10 0.68033904
11 0.6765314
12 0.67277724
13 0.6690557
14 0.665363
15 0.6616981
16 0.6580607
17 0.6544506
18 0.6508674
19 0.6473108
20 0.64378065
21 0.64027673
22 0.6367986
23 0.63334614
24 0.62991923
25 0.62651736
26 0.62314045
27 0.6197882
28 0.6164606
29 0.61315715
30 0.6098779
31 0.6066225
32 0.60339063
33 0.6001823
34 0.5969973
35 0.5938352
36 0.59069616
37 0.58757967
38 0.5844857
39 0.58141416
40 0.5783647
41 0.5753371
42 0.5723314
43 0.5693473
44 0.5663846
45 0.56344324
46 0.56052285
47 0.55762357
48 0.55474496
49 0.551887
50 0.54904944
51 0.5462322
52 0.54343516
53 0.54065806
54 0.5379008
55 0.53516334
56 0.53244525
57 0.52974653
58 0.5270671
59 0.5244068
60 0.5217653
61 0.5191427
62 0.51653874
63 0.51395327
64 0.5113862
65 0.5088374
66 0.5063066
67 0.5037938
68 0.5012988
69 0.49882153
70 0.49636176
71 0.4939194
72 0.4914944
73 0.4890864
74 0.4866955
75 0.4843

In [9]:
sess.run( w)

array([[0.9401207],
       [0.9401207]], dtype=float32)

In [10]:
sess.run(b)

array([-6.115953], dtype=float32)

In [11]:
result = sess.run( hx, {x:[[3,5]]})

In [12]:
result>0.5

array([[ True]])

In [13]:
t = tf.cast( result>0.5, dtype=tf.int32)
sess.run(t)

array([[1]])

In [14]:
h = sess.run( hx, {x:xdata})

In [15]:
ydata

[[0], [0], [0], [1], [1], [1]]

In [16]:
(h>0.5)

array([[False],
       [False],
       [False],
       [ True],
       [ True],
       [ True]])

In [17]:
((h>0.5) == ydata).mean() #정확도 100%

1.0

In [18]:
h

array([[0.08663195],
       [0.08663195],
       [0.08663195],
       [0.9639194 ],
       [0.9639194 ],
       [0.9639194 ]], dtype=float32)

In [19]:
predict = tf.cast( h>0.5, dtype=tf.float32)
e= tf.equal( predict, y) # predict == y
m = tf.reduce_mean( tf.cast(e,dtype=tf.float32) )
sess.run( m)

1.0

In [20]:
predict = tf.cast( h>0.5, dtype=tf.float32)
m = tf.reduce_mean( tf.cast(tf.equal( predict, y),dtype=tf.float32) )
sess.run( m)

1.0

In [21]:
sess.run( predict )

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.]], dtype=float32)