In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
from sklearn import datasets
import seaborn as sns
from sklearn import preprocessing

In [2]:
data = sns.load_dataset('titanic')
data

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

### fare(승선가격),sex(성별)에 따른 생존유무를 예측하시요
#### w,b,를 구하고, 정확도를 구하시요.

In [3]:
# data.where( data['sex']=='male',1,0)

In [4]:
data["Sex_encode"]=np.where( data['sex']=='male', 1,0 )
data

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  Sex_encode  
0      man        True  NaN  Southampton    no  False           1  
1    woman       False    C    Cherbourg   yes  False           0  
2    woman       False  NaN  Southampton   yes   True           0  
3    woman       False    C  Southampton   yes  False           0  
4      man        True  NaN  Southampton    no   True           1  
..     ...         ...  ...          ...   ...    ...         ...  
886    man        True  NaN  Southampton    no   True           1  
887  woman       False    B  Southampton   yes   True           0  
888  woman       False  NaN  Southampton    no  False           0  
889    man        True    C    Cherbourg   yes   True           1  
890    man        True  NaN   Queenstown    no   True           1  

[891 rows x 16 columns]

In [5]:
# data.loc[data["sex"] == "male", "Sex_encode"] = 0
# data.loc[data["sex"] == "female", "Sex_encode"] = 1
# data

In [6]:
xdata = data[['Sex_encode','fare']]
ydata = data[['survived']]

In [7]:
# dim = 입력 갯수
IO = Dense( units=1, input_dim=2,activation='sigmoid')
model = Sequential([IO])
model.compile(loss='binary_crossentropy',
             optimizer=Adam(0.1),metrics=['accuracy'])
h = model.fit(xdata,ydata,epochs=100)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 891 samples
Epoch 1/100
891/891 [==============================] - 0s 111us/sample - loss: 7.0419 - acc: 0.4164
Epoch 2/100
891/891 [==============================] - 0s 35us/sample - loss: 1.0454 - acc: 0.6072
Epoch 3/100
891/891 [==============================] - 0s 25us/sample - loss: 0.8025 - acc: 0.6914
Epoch 4/100
891/891 [==============================] - 0s 27us/sample - loss: 0.8246 - acc: 0.6813
Epoch 5/100
891/891 [==============================] - 0s 28us/sample - loss: 0.5855 - acc: 0.7329
Epoch 6/100
891/891 [==============================] - 0s 24us/sample - loss: 0.5625 - acc: 0.7699
Epoch 7/100
891/891 [==============================] - 0s 29us/sample - loss: 0.5264 - acc: 0.7800
Epoch 8/100
891/891 [==============================] - 0s 26us/sample - loss: 0.5376 - acc: 0.7722
Epoch 9/100

In [8]:
model.predict(xdata)

array([[0.09360367],
       [0.95727015],
       [0.6586704 ],
       [0.9172486 ],
       [0.09626347],
       [0.09764683],
       [0.36725467],
       [0.14989644],
       [0.6860094 ],
       [0.8197069 ],
       [0.73045766],
       [0.7986884 ],
       [0.09626347],
       [0.2073952 ],
       [0.6580542 ],
       [0.7250911 ],
       [0.19405118],
       [0.11426511],
       [0.740247  ],
       [0.6525544 ],
       [0.17583454],
       [0.11426511],
       [0.6595764 ],
       [0.2355558 ],
       [0.7624661 ],
       [0.8271148 ],
       [0.09352162],
       [0.99951285],
       [0.65827185],
       [0.09574559],
       [0.1856938 ],
       [0.99757785],
       [0.6571463 ],
       [0.10483319],
       [0.6522274 ],
       [0.368492  ],
       [0.09353536],
       [0.09626347],
       [0.740247  ],
       [0.68691224],
       [0.6720245 ],
       [0.76194   ],
       [0.09574559],
       [0.87650156],
       [0.65827185],
       [0.09626347],
       [0.12442774],
       [0.657

In [9]:
model.predict_classes(np.array([[1,53]]))

array([[0]])

In [10]:
h.history['acc'][-1]

0.7418631

In [11]:
x = tf.placeholder(tf.float32,shape=[None,2])
y = tf.constant( ydata, tf.float32)
w = tf.Variable( tf.random_uniform([2,1]))
b = tf.Variable(tf.random_uniform([1]))

z = tf.matmul(x,w) +b
hx = tf.nn.sigmoid(z)

cost_i=tf.nn.sigmoid_cross_entropy_with_logits(logits=z, labels=y)

cost = tf.reduce_mean ( tf.square(hx-y) )

optimizer = tf.train.AdamOptimizer(0.1) #Learning rate
train = optimizer.minimize(cost)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

for i in range( 1000):
    sess.run( train, {x:xdata})
    print( i, sess.run(cost, {x:xdata}))

0 0.5976815
1 0.5862592
2 0.5628766
3 0.5185807
4 0.44408247
5 0.334289
6 0.19753586
7 0.3254103
8 0.3531729
9 0.36464882
10 0.37061194
11 0.37409008
12 0.37627745
13 0.37773082
14 0.37873808
15 0.3794599
16 0.37999088
17 0.38038963
18 0.38069388
19 0.3809287
20 0.38111103
21 0.3812528
22 0.38136283
23 0.38144708
24 0.3815102
25 0.38155556
26 0.38158575
27 0.38160256
28 0.38160747
29 0.38160163
30 0.3815856
31 0.38155997
32 0.38152486
33 0.38148052
34 0.38142654
35 0.38136283
36 0.38128892
37 0.38120398
38 0.38110712
39 0.38099712
40 0.3808727
41 0.38073173
42 0.38057217
43 0.38039097
44 0.38018477
45 0.37994906
46 0.37967828
47 0.379365
48 0.37900016
49 0.3785714
50 0.37806234
51 0.3774506
52 0.37670508
53 0.3757813
54 0.37461329
55 0.37310034
56 0.37108013
57 0.36827564
58 0.36417577
59 0.35772735
60 0.34637535
61 0.32181966
62 0.19662535
63 0.24741182
64 0.31608465
65 0.3482239
66 0.35587528
67 0.34507543
68 0.32068253
69 0.2870476
70 0.24535434
71 0.19946106
72 0.18292525
73 0.2811

In [12]:
sess.run(w)

array([[-2.375358  ],
       [ 0.01289224]], dtype=float32)

In [13]:
sess.run(b)

array([0.6461449], dtype=float32)

In [14]:
result = sess.run(hx, {x:[[1,53]]})
result

array([[0.26000842]], dtype=float32)