In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
titanic = sns.load_dataset('titanic')
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [18]:
titanic['sex']= np.where(titanic['sex']=='female','1','0')
titanic

survived  pclass sex   age  sibsp  parch     fare embarked   class  \
0           0       3   0  22.0      1      0   7.2500        S   Third   
1           1       1   1  38.0      1      0  71.2833        C   First   
2           1       3   1  26.0      0      0   7.9250        S   Third   
3           1       1   1  35.0      1      0  53.1000        S   First   
4           0       3   0  35.0      0      0   8.0500        S   Third   
..        ...     ...  ..   ...    ...    ...      ...      ...     ...   
886         0       2   0  27.0      0      0  13.0000        S  Second   
887         1       1   1  19.0      0      0  30.0000        S   First   
888         0       3   1   NaN      1      2  23.4500        S   Third   
889         1       1   0  26.0      0      0  30.0000        C   First   
890         0       3   0  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [21]:
titanic['alive']= np.where(titanic['alive']=='yes','1','0')
titanic

survived  pclass sex   age  sibsp  parch     fare embarked   class  \
0           0       3   0  22.0      1      0   7.2500        S   Third   
1           1       1   1  38.0      1      0  71.2833        C   First   
2           1       3   1  26.0      0      0   7.9250        S   Third   
3           1       1   1  35.0      1      0  53.1000        S   First   
4           0       3   0  35.0      0      0   8.0500        S   Third   
..        ...     ...  ..   ...    ...    ...      ...      ...     ...   
886         0       2   0  27.0      0      0  13.0000        S  Second   
887         1       1   1  19.0      0      0  30.0000        S   First   
888         0       3   1   NaN      1      2  23.4500        S   Third   
889         1       1   0  26.0      0      0  30.0000        C   First   
890         0       3   0  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton     0  False  
1    woman       False    C    Cherbourg     1  False  
2    woman       False  NaN  Southampton     1   True  
3    woman       False    C  Southampton     1  False  
4      man        True  NaN  Southampton     0   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton     0   True  
887  woman       False    B  Southampton     1   True  
888  woman       False  NaN  Southampton     0  False  
889    man        True    C    Cherbourg     1   True  
890    man        True  NaN   Queenstown     0   True  

[891 rows x 15 columns]

In [22]:
xdata = titanic.iloc[:,[2,6]]
ydata = titanic.iloc[:,[-2]]

In [23]:
IO = Dense(units=1, input_dim=2, activation='sigmoid') #sigmoid를 활성함수로 쓰겠다. 
model = Sequential( [IO] ) #순차모델
model.compile( loss='binary_crossentropy', optimizer=Adam(0.1),metrics=['accuracy'])  #loss는 로그 함수를 사용한다. 
h = model.fit( xdata, ydata, epochs=1000)

Train on 891 samples
Epoch 1/1000
891/891 [==============================] - 0s 122us/sample - loss: 0.9079 - acc: 0.6644
Epoch 2/1000
891/891 [==============================] - 0s 25us/sample - loss: 0.5267 - acc: 0.7767
Epoch 3/1000
891/891 [==============================] - 0s 26us/sample - loss: 0.5801 - acc: 0.7576
Epoch 4/1000
891/891 [==============================] - 0s 23us/sample - loss: 0.6150 - acc: 0.7497
Epoch 5/1000
891/891 [==============================] - 0s 26us/sample - loss: 0.5387 - acc: 0.7733
Epoch 6/1000
891/891 [==============================] - 0s 20us/sample - loss: 0.5736 - acc: 0.7767
Epoch 7/1000
891/891 [==============================] - 0s 34us/sample - loss: 0.7038 - acc: 0.7385
Epoch 8/1000
891/891 [==============================] - 0s 32us/sample - loss: 0.5780 - acc: 0.7699
Epoch 9/1000
891/891 [==============================] - 0s 33us/sample - loss: 0.5197 - acc: 0.7834
Epoch 10/1000
891/891 [==============================] - 0s 34us/sample - loss

In [24]:
model.predict(xdata)

array([[0.09674203],
       [0.48582512],
       [0.60148895],
       [0.5194174 ],
       [0.09622642],
       [0.09596422],
       [0.07150701],
       [0.08817178],
       [0.5957903 ],
       [0.5616734 ],
       [0.5858419 ],
       [0.5680708 ],
       [0.09622642],
       [0.0822947 ],
       [0.6016145 ],
       [0.5870969 ],
       [0.08350304],
       [0.09309068],
       [0.5835082 ],
       [0.6027287 ],
       [0.08528817],
       [0.09309068],
       [0.6013043 ],
       [0.07996637],
       [0.57797337],
       [0.5592755 ],
       [0.09675813],
       [0.01591212],
       [0.6015701 ],
       [0.09632561],
       [0.08430099],
       [0.351393  ],
       [0.6017991 ],
       [0.09466276],
       [0.05798557],
       [0.07143959],
       [0.09675542],
       [0.09622642],
       [0.5835082 ],
       [0.5955973 ],
       [0.59873915],
       [0.5781086 ],
       [0.09632561],
       [0.5406298 ],
       [0.6015701 ],
       [0.09622642],
       [0.09154204],
       [0.601

In [27]:
model.predict_classes(xdata)

array([[0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
    

In [31]:
IO.get_weights()

[array([[ 2.6506236 ],
        [-0.00739268]], dtype=float32),
 array([-2.1803634], dtype=float32)]

In [32]:
model.predict( np.array( [[0,53]] ) )

array([[0.07095077]], dtype=float32)

In [33]:
h.history['acc'][-1]

0.75420874