In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt

In [2]:
arr = np.loadtxt('data/softmax.txt')

In [3]:
xdata = arr[:,1:3]
ydata = arr[:,3:]

In [4]:
x = tf.placeholder(tf.float32,[None,2])
y = tf.constant( ydata, tf.float32)

In [5]:
w = tf.Variable( tf.random_uniform([2,3]) )#[f갯수,분류3]
b = tf.Variable( tf.random_uniform([3]) )

In [6]:
z = tf.matmul(x,w) + b
hx = tf.nn.softmax( z )
cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits=z,
                                            labels=y)
cost = tf.reduce_mean(cost_i)

In [7]:
optimizer = tf.train.GradientDescentOptimizer(0.1)#learning rate
train = optimizer.minimize( cost )
sess = tf.Session()
init =tf.global_variables_initializer()
sess.run( init)

In [8]:
for i in range(1000):
    sess.run( train, {x:xdata})
    print( i, sess.run( cost, {x:xdata}))

0 1.1454005
1 1.1333292
2 1.1242182
3 1.1166766
4 1.1098144
5 1.10339
6 1.0972378
7 1.0912933
8 1.0855156
9 1.0798848
10 1.0743878
11 1.0690166
12 1.0637652
13 1.0586286
14 1.0536025
15 1.0486832
16 1.0438671
17 1.0391507
18 1.0345309
19 1.0300045
20 1.0255684
21 1.0212196
22 1.0169554
23 1.012773
24 1.0086699
25 1.0046432
26 1.0006909
27 0.9968103
28 0.99299926
29 0.98925555
30 0.985577
31 0.9819615
32 0.9784072
33 0.97491217
34 0.97147477
35 0.9680929
36 0.9647651
37 0.96148956
38 0.95826495
39 0.9550897
40 0.9519624
41 0.94888145
42 0.94584566
43 0.9428539
44 0.93990475
45 0.93699706
46 0.93412983
47 0.9313017
48 0.92851186
49 0.9257591
50 0.92304254
51 0.92036134
52 0.9177145
53 0.91510105
54 0.9125205
55 0.9099716
56 0.9074538
57 0.9049665
58 0.9025086
59 0.9000799
60 0.8976793
61 0.8953064
62 0.89296055
63 0.890641
64 0.8883473
65 0.8860789
66 0.8838353
67 0.88161576
68 0.8794199
69 0.8772476
70 0.87509775
71 0.87297034
72 0.8708648
73 0.8687807
74 0.8667175
75 0.8646751
76 0.862

In [9]:
sess.run(w)

array([[ 0.39677128,  0.25706723,  0.11372018],
       [ 1.3864228 ,  0.7672605 , -0.36972106]], dtype=float32)

In [10]:
sess.run(b)

array([-4.3558254 ,  0.04588697,  5.031355  ], dtype=float32)

In [11]:
sess.run( hx, {x:[[6,6]]})

array([[0.521542  , 0.44822904, 0.03022896]], dtype=float32)

In [12]:
sess.run( z, {x:[[6,6]]})

array([[6.343339 , 6.1918535, 3.4953496]], dtype=float32)

In [13]:
h =sess.run( hx, {x:[[6,6]]})
int( h.argmax(axis=1) )

0

In [14]:
grade = ['A','B','C']
grade[ int(h.argmax(axis=1)) ]

'A'

In [15]:
#공부한 시간,출석일수 6,6 1,1
# hh= sess.run( hx, {x:[[6,6],[1,1]]})
hh= sess.run( z, {x:[[6,6],[1,1]]})
hh.argmax(axis=1)

array([0, 2], dtype=int64)

In [16]:
myarr = np.array([[1,2,3],[3,4,5]])
myarr

array([[1, 2, 3],
       [3, 4, 5]])

In [17]:
myarr.sum()

18

In [18]:
myarr.argmax() #[1,2,3,3,4,5]

5

In [19]:
myarr.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [20]:
myarr.argmax(axis=1)

array([2, 2], dtype=int64)