## 7. 나이,성별, 운임(fair), 등급(class)에 따른 생사을 예측하시요(텐서, 케라스)
( train, test 구분하고, 정확도 측정결과도 출력해야함)

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from sklearn import datasets, model_selection
from tensorflow.keras.backend import one_hot

In [2]:
df = pd.read_csv('data/titanic.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
df.keys()

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
df['Sex_encode'] = np.where(df['Sex']=='female',1,0)
df[['Age','Pclass','Sex_encode','Fare']]

Age  Pclass  Sex_encode     Fare
0    22.0       3           0   7.2500
1    38.0       1           1  71.2833
2    26.0       3           1   7.9250
3    35.0       1           1  53.1000
4    35.0       3           0   8.0500
..    ...     ...         ...      ...
886  27.0       2           0  13.0000
887  19.0       1           1  30.0000
888   NaN       3           1  23.4500
889  26.0       1           0  30.0000
890  32.0       3           0   7.7500

[891 rows x 4 columns]

In [5]:
df[df["Age"].isnull()]

PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James   
17            18         1       2              Williams, Mr. Charles Eugene   
19            20         1       3                   Masselmani, Mrs. Fatima   
26            27         0       3                   Emir, Mr. Farred Chehab   
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex  Age  SibSp  Parch      Ticket     Fare Cabin Embarked  Sex_encode  
5      male  NaN      0      0      330877   8.4583   NaN        Q           0  
17     male  NaN      0      0      244373  13.0000   NaN        S           0  
19   female  NaN      0      0        2649   7.2250   NaN        C           1  
26     male  NaN      0      0        2631   7.2250   NaN        C           0  
28   female  NaN      0      0      330959   7.8792   NaN        Q           1  
..      ...  ...    ...    ...         ...      ...   ...      ...         ...  
859    male  NaN      0      0        2629   7.2292   NaN        C           0  
863  female  NaN      8      2    CA. 2343  69.5500   NaN        S           1  
868    male  NaN      0      0      345777   9.5000   NaN        S           0  
878    male  NaN      0      0      349217   7.8958   NaN        S           0  
888  female  NaN      1      2  W./C. 6607  23.4500   NaN        S           1  

[177 rows x 13 columns]

In [6]:
df['Age'].mean()

29.69911764705882

In [7]:
df['Age'] = df['Age'].fillna(29)

In [8]:
df[df["Age"].isnull()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, Sex_encode]
Index: []

In [9]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Sex_encode  
0        0         A/5 21171   7.2500   NaN        S           0  
1        0          PC 17599  71.2833   C85        C           1  
2        0  STON/O2. 3101282   7.9250   NaN        S           1  
3        0            113803  53.1000  C123        S           1  
4        0            373450   8.0500   NaN        S           0  
..     ...               ...      ...   ...      ...         ...  
886      0            211536  13.0000   NaN        S           0  
887      0            112053  30.0000   B42        S           1  
888      2        W./C. 6607  23.4500   NaN        S           1  
889      0            111369  30.0000  C148        C           0  
890      0            370376   7.7500   NaN        Q           0  

[891 rows x 13 columns]

In [10]:
xdata = df[['Age','Pclass','Sex_encode','Fare']]
ydata = to_categorical(df['Survived'],2)

In [11]:
x_train,x_test, y_train,y_test =model_selection.train_test_split( xdata,ydata, 
                                                                 test_size=0.3)

In [12]:
x_train.shape

(623, 4)

In [13]:
x_test.shape

(268, 4)

In [14]:
y_train.shape

(623, 2)

In [15]:
y_test.shape

(268, 2)

In [16]:
ydata

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [17]:
x = tf.placeholder(tf.float32,[None,4])
y = y_train
w = tf.Variable(tf.random_uniform([4,2]))
b = tf.Variable(tf.random_uniform([2]))

In [18]:
z = tf.matmul(x,w) + b
hx = tf.nn.softmax(z)
cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits= z,
                                            labels=y) #logits 인자에는 hx함수 , labels= Tensor형 yvalue
cost = tf.reduce_mean(cost_i)

In [19]:
optimizer = tf.train.GradientDescentOptimizer(0.1) #learning rate
train = optimizer.minimize(cost)
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [20]:
for i in range(1000):
    sess.run(train,{x:x_train}) #벼림 연산 # w = w.assign(w-0.1*g)
    c = sess.run(cost,{x:x_train }) 
    print(i,c)

0 40.40066
1 41.42245
2 31.692501
3 19.097176
4 12.384419
5 6.0507536
6 6.52743
7 91.79687
8 10.8263235
9 4.525539
10 9.108073
11 86.07818
12 15.122185
13 27.9486
14 58.12238
15 23.049875
16 13.882216
17 7.626644
18 9.352256
19 85.17365
20 15.577375
21 16.279203
22 45.8801
23 32.05609
24 38.16013
25 32.01221
26 19.112509
27 12.480149
28 6.1275125
29 5.3606286
30 91.90473
31 10.88382
32 4.5833287
33 8.698757
34 86.57839
35 14.707857
36 27.53574
37 58.490105
38 22.835241
39 13.742675
40 7.569286
41 9.859516
42 84.484
43 15.70903
44 16.799448
45 45.639263
46 31.7567
47 36.957314
48 32.38497
49 19.211899
50 12.554047
51 6.1941724
52 4.2772393
53 90.62211
54 10.78179
55 4.4081182
56 4.87113
57 14.870181
58 8.481622
59 2.2108333
60 15.831926
61 85.2277
62 8.616723
63 10.15593
64 82.269516
65 16.665453
66 15.509181
67 33.642036
68 46.80651
69 34.286346
70 22.874596
71 13.776185
72 7.566656
73 8.131261
74 85.90506
75 15.013106
76 14.437831
77 39.528778
78 41.319252
79 38.864067
80 31.873413
81

In [21]:
t = sess.run( hx, {x:x_test})

In [22]:
a = t.argmax( axis=1)

In [23]:
b = y_test.argmax(axis=1)

In [24]:
(a==b).mean()

0.6791044776119403

In [32]:
result = sess.run(hx,{x:[[35,1,53.1,1]]})
result.argmax(axis=1)

array([1], dtype=int64)

In [34]:
IO = Dense( units=2, input_dim =4, activation='softmax' )
model = Sequential( [IO])
model.compile( loss='categorical_crossentropy',optimizer=Adam(0.1),metrics=['accuracy'])
h = model.fit( xdata, ydata, epochs = 1000)

Train on 891 samples
Epoch 1/1000
891/891 [==============================] - 0s 65us/sample - loss: 9.1504 - acc: 0.5533
Epoch 2/1000
891/891 [==============================] - 0s 40us/sample - loss: 1.4452 - acc: 0.6992
Epoch 3/1000
891/891 [==============================] - 0s 39us/sample - loss: 0.9271 - acc: 0.7374
Epoch 4/1000
891/891 [==============================] - 0s 40us/sample - loss: 0.7100 - acc: 0.7407
Epoch 5/1000
891/891 [==============================] - 0s 39us/sample - loss: 0.8135 - acc: 0.7239
Epoch 6/1000
891/891 [==============================] - 0s 37us/sample - loss: 0.8384 - acc: 0.7430
Epoch 7/1000
891/891 [==============================] - 0s 36us/sample - loss: 0.6067 - acc: 0.7621
Epoch 8/1000
891/891 [==============================] - 0s 25us/sample - loss: 0.7396 - acc: 0.7262
Epoch 9/1000
891/891 [==============================] - 0s 29us/sample - loss: 0.6357 - acc: 0.7464
Epoch 10/1000
891/891 [==============================] - 0s 34us/sample - loss:

In [35]:
IO.get_weights()

[array([[ 0.6304745 ,  0.61142427],
        [ 0.9257388 , -0.4792235 ],
        [-1.897863  ,  1.1599365 ],
        [-0.09685533, -0.08026369]], dtype=float32),
 array([-1.3504955,  1.3504975], dtype=float32)]

In [41]:
model.predict(np.array([[35,1,1,53.1]])) # hx값

array([[0.01027119, 0.9897288 ]], dtype=float32)

In [42]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Sex_encode  
0        0         A/5 21171   7.2500   NaN        S           0  
1        0          PC 17599  71.2833   C85        C           1  
2        0  STON/O2. 3101282   7.9250   NaN        S           1  
3        0            113803  53.1000  C123        S           1  
4        0            373450   8.0500   NaN        S           0  
..     ...               ...      ...   ...      ...         ...  
886      0            211536  13.0000   NaN        S           0  
887      0            112053  30.0000   B42        S           1  
888      2        W./C. 6607  23.4500   NaN        S           1  
889      0            111369  30.0000  C148        C           0  
890      0            370376   7.7500   NaN        Q           0  

[891 rows x 13 columns]

In [43]:
h.history['acc'][-1]

0.74971944

In [44]:
h = model.predict(xdata)
(h.argmax(axis=1) == df['Survived']).mean()

0.7519640852974186