In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([10,20]) # vector
b = tf.constant([1,2])

In [5]:
c = tf.subtract(a,b) # a-b

In [6]:
sess = tf.Session()

In [7]:
sess.run(c) # element wise(여소별 연산)

array([ 9, 18])

In [8]:
d = tf.mod(a,b) # a % b

In [9]:
sess.run(d)

array([0, 0])

In [10]:
e = tf.divide(a,b) # a / b

In [11]:
sess.run(e)

array([10., 10.])