In [1]:
import tensorflow as tf

In [10]:
a= tf.constant([[1,2,3],[4,5,6]])
# b= tf.constant(10)
# b = tf.constant([10,11,12]) # broadcasting: 없는 수를 확장시켜주는 개념
# b = tf.constant([[10,11]]) # broadcasting X
b = tf.constant([[10],[11]]) # broadcasting 가능

In [11]:
c = a + b #tf.add(a,b)

In [12]:
sess = tf.Session()

In [13]:
sess.run(c)

array([[11, 12, 13],
       [15, 16, 17]])

In [14]:
x = tf.constant([[1,2],[3,4]])
y = tf.constant([[5,6],[7,8]])


In [15]:
# 대부분의 다른연산 element wise
z = tf.matmul(x,y) #matrix (행열곱)

In [17]:
y = tf.multiply(x,y)

In [19]:
sess.run(y)

array([[ 5, 12],
       [21, 32]])

In [18]:
sess.run(z) #matrix multiply (행렬곱)

array([[19, 22],
       [43, 50]])