In [1]:
import tensorflow as tf

In [2]:
#1<= n <7 1 ~ 6 까지...
x = tf.random_uniform([10,1], minval=1, maxval=7, dtype=tf.int32)

In [3]:
sess = tf.Session()

In [4]:
sess.run(x)

array([[6],
       [1],
       [4],
       [2],
       [5],
       [2],
       [6],
       [5],
       [3],
       [1]])

In [6]:
c = tf.constant( [[1],[2]]) #2x1
d = tf.constant( [[3],[4]])
# r = tf.concat( [c,d] ,axis=0) #행으로 결합
r = tf.concat( [c,d] ,axis=1) #열로 결합

In [7]:
sess.run(r)

array([[1, 3],
       [2, 4]])

In [ ]:
# 주사위 2개를 10번굴리기를 시행 했을때 
# 10x3 매트릭스 텐서를 생성하시요
# 1열과 2열은 주사위를 시행했을 때 값이며 
# 3열은 두개열의 합으로 구성된다.

In [15]:
d1 = tf.random_uniform([10,1], minval=1, maxval=7, dtype=tf.int32)
d2 = tf.random_uniform([10,1], minval=1, maxval=7, dtype=tf.int32)
dsum = tf.add(x,y)

In [16]:
result = tf.concat([d1,d2,dsum], axis=1)

In [18]:
sess.run(result)

array([[ 5,  1,  4],
       [ 2,  6, 11],
       [ 2,  6,  6],
       [ 6,  6, 10],
       [ 2,  2,  6],
       [ 3,  6,  7],
       [ 3,  4,  6],
       [ 4,  6,  6],
       [ 4,  5,  3],
       [ 5,  1,  5]])